### DISCUSSION TITLE
Hint Position

### DISCUSSION THREAD

**Discussion by getrealwealth** [filamentphp/filament#11300] [Ideas]
It would be useful to have an option to position Hint Icon right after the Label name instead of at the end. So `justify-start` instead of `justify-between`.
Reason is that if form element is not very wide but still require `columnSpanFull` for UI - then the hint icon looks out of the place.
Something like this: 
![image](https://github.com/filamentphp/filament/assets/56085825/a32a46b0-64d4-4dba-9a2d-dd45b5fa380d)

**Comment by gboquizosanchez** [comment]
I have solved this with a custom theme in CSS:

```css
.fi-fo-field-wrp > .grid > .justify-between {
  justify-content: flex-start !important;
}
```
