### DISCUSSION TITLE
Vertically Align Action Table

### DISCUSSION THREAD

**Discussion by untillnesss** [filamentphp/filament#12040] [Help] [answered]
### Package

Table builder

### Package Version

v3.x.x

### How can we help you?

![image](https://github.com/filamentphp/filament/assets/33585758/ee2b17b3-8ad9-4672-a5c4-000a6521e254)

I want to position the Action Table button at the top like other columns, how do I do that?

**Comment by dissto** [comment, marked as answer]
Here is one solution:

Add a custom class to make it easier to only target the given resource.

```php
$table
  ->recordClasses('my-custom-class-whatever')
```

And in your css you can add:

```css 
.my-custom-class-whatever .fi-ta-actions-cell {
    vertical-align: top;
}
```

There are probably better options though 😁
