### DISCUSSION TITLE
Vertical navigation for Wizard

### DISCUSSION THREAD

**Discussion by vikijel** [filamentphp/filament#13894] [Showcase]
I have created a piece of CSS that turns the Wizard into vertical

It is activated by adding class `fi-fo-wizard-vertical` to the wizard using:

```php
Wizard::make(...)->extraAttributes(['class' => 'fi-fo-wizard-vertical'])
```

CSS (you can adjust the grid-cols-* and col-span-* for different width ratios then 2:6)
```css
.fi-fo-wizard-vertical {
    @apply grid md:grid-cols-8
}

.fi-fo-wizard-vertical .fi-fo-wizard-header {
    grid-auto-flow: row !important;
    align-content: flex-start;
    @apply md:divide-y !important;
    @apply border-b-0 border-e;
    @apply md:col-span-2
}

.fi-fo-wizard-vertical .fi-fo-wizard-header-step {
    @apply block
}

.fi-fo-wizard-vertical .fi-fo-wizard-header-step-button {
    @apply w-full
}

.fi-fo-wizard-vertical .fi-fo-wizard-header-step-separator {
    display: none !important;
}

.fi-fo-wizard-vertical .fi-fo-wizard-step {
    @apply md:col-span-6
}

.fi-fo-wizard-vertical > div:last-child {
    @apply md:col-span-8 border-t pt-6
}
``` 

Default style:
![wizard_default](https://github.com/user-attachments/assets/9f58d209-c14f-4280-b8e7-d229c1509bf9)

Vertical style:
![wizard_vertical](https://github.com/user-attachments/assets/06560ae9-6394-47a7-875b-d3bf9334a278)

PS: 
I tried to rotate & stretch the separator svg, but after 2 hours got mad and decided to hide it instead :)

**Comment by vikijel** [comment]
This could be turned into built-in feature by adding `->vertical()` method to the Wizard + the piece of css,

Adding class fi-fo-wizard-actions to the buttons wrapper div would be handy, now i had to use the :last-child

And [ability to add buttons](https://github.com/filamentphp/filament/discussions/13660) would be nice too

**Comment by vikijel** [comment]
PR to add `Wizard->vertical()` method for more native style toggle: https://github.com/filamentphp/filament/pull/13919

**Reply by vikijel** [reply]
Didn't realize features are freezed for v3, so use the CSS override above for now.

**Comment by Jubeki** [comment]
Thanks for the css styling!

Here is the styling I use for filament v4:

```css

.fi-sc-wizard-vertical {
    @apply grid md:grid-cols-4
}

.fi-sc-wizard-vertical .fi-sc-wizard-header {
    grid-auto-flow: row !important;
    align-content: flex-start;
    @apply md:!divide-y divide-slate-200 border-b-0 border-e
}

.fi-sc-wizard-vertical .fi-sc-wizard-header-step {
    @apply block
}

.fi-sc-wizard-vertical .fi-sc-wizard-header-step-button {
    @apply w-full
}

.fi-sc-wizard-vertical .fi-sc-wizard-header-step-separator {
    display: none !important;
}

.fi-sc-wizard-vertical .fi-sc-wizard-step {
    @apply md:col-span-3
}

.fi-sc-wizard-vertical > div:last-child {
    @apply md:col-span-4 border-slate-200 border-t pt-6
}
```

in the AppServiceProvider, I then configure all my Wizards to use the vertical styling (which of course it optional if you don't want every wizard to be use the vertical styling):

```php
Wizard::configureUsing(function(Wizard $component) {
    $component->extraAttributes(['class' => 'fi-sc-wizard-vertical']);
});
```
