### DISCUSSION TITLE
Row hover covers full row

### DISCUSSION THREAD

**Discussion by joostvanhoof** [filamentphp/filament#14640] [Ideas]
Don't think this is really a 'bug' as such, but at least it could be a nice improvement. I noticed that if you make a row clickable using `recordUrl()` and user hovers a row, the hoverable / clickable area for the row will be determined by the content in the cell that you're hovering.

This becomes especially apparent when the user hovers a cell that less content than another cell in the same row.

I made a screen recording where you can very clearly see that a user can only click the row if actual content + it's padding is hovered, but not the actual full row (pay close attention to when the cursor changes from arrow to hand icon).

![row-hover](https://github.com/user-attachments/assets/833109e6-ce8e-4104-aa4c-2d702ef1916c)

**Comment by arnaudliperini** [comment]
Effectively, I fixed it by adding this css code :

``` css
tr.fi-ta-row {
    height: 1px;
}

td.fi-ta-cell {
    height: inherit;
}

td.fi-ta-cell .fi-ta-col-wrp {
    height: 100%;
}

td.fi-ta-cell a {
    height: 100%;
    align-items: center;
}
```

But update the Blade view could be better with the appropriate Tailwind classes.

I would be happy to submit a pull request if desired.

Thank you for your consideration and for your excellent work on the project.
