### DISCUSSION TITLE
export does not save files in volume but in overlay2 on docker

### DISCUSSION THREAD

**Discussion by gzai** [filamentphp/filament#16325] [Help]
### Package

Actions

### Package Version

v3.3.14

### How can we help you?

I have a filament v3.3.14 using docker nginx, php-fpm, mysql, volumes and others.

I want to export data from a component and the export job is completed in the queue. But after I click the notification for the export result, I'm redirected to http://domain/filament/exports/1/download?format=xlsx with a 404 error display.

After deep search, when export job is completed and the result file is not stored to docker volume dashboard_storage, but to docker overlay2.

When a folder containing the export file result folder ``/1`` is not created inside /storage/app/filament_exports/, a 404 error will appear.

How to fix this issue?

![image](https://github.com/user-attachments/assets/1bb8e3a6-acc3-452b-b095-bdf9037ffa50)

docker-compose.yml:
```
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard_app
    image: dashboard:latest
    volumes:
      - dashboard_storage:/var/www/storage
    depends_on:
      - mysql
    networks:
      - app_network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Nginxfile
    container_name: dashboard_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - dashboard_storage:/var/www/storage
    depends_on:
      - app
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: dashboard_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  dashboard_storage:
  mysql_data:

networks:
  app_network:
    driver: bridge
```
