### DISCUSSION TITLE
Need help to load my theme

### DISCUSSION THREAD

**Discussion by tanthammar** [filamentphp/filament#2703] [Help] [answered]
I've added "success, primary ..." colors to` tailwind.config.js` and some classes to my app.css.

Then I added this to my `AppServiceProvider` `boot` method

```php
Filament::serving(static function () {
                Filament::registerTheme(mix('css/app.css'));
            });
```

The colors and my custom classes aren't loaded into Filament Admin panel.

What did I miss?

**Comment by danharrin** [comment]
What's the contents of your CSS file?

**Comment by tanthammar** [comment]
app.css

```css
@import '../../vendor/filament/forms/dist/module.esm.css';
@import '../../node_modules/tippy.js/dist/tippy.css';
@import '../../node_modules/tippy.js/themes/light.css';

@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'custom.css';
@import 'theme.css';
@import 'tailwindcss/utilities';
```

custom.css
just some simple classes with custom names, example

```css
.nosy {
    position: absolute;
    opacity: 0;
}
```

theme.css
```css
/* @override: @tailwindcss/forms */
@layer base {
    [dir='rtl'] select {
        background-position: left 0.5rem center !important;
        padding-left: 2.5rem;
        padding-right: 0.75rem;
    }

    :root.dark {
        color-scheme: dark;
    }
}

@layer components {
    .filament-login-page {
        @apply relative bg-no-repeat;
        background-image: radial-gradient(
            circle at top,
            theme('colors.primary.100'),
            theme('colors.white') 50%
        );
    }

    .dark .filament-login-page {
        background-image: radial-gradient(
            circle at top,
            theme('colors.primary.800'),
            theme('colors.gray.800'),
            theme('colors.gray.900') 100%
        );
    }

    .filament-login-page form::before {
        @apply w-2/3 absolute inset-x-0 h-px mx-auto bg-gradient-to-r from-gray-200 via-primary-400 to-gray-200 dark:from-gray-700 dark:via-primary-400 dark:to-gray-700;
        content: '';
        z-index: 1;
        top: -1px;
    }
}
```

tailwind.config
```js
const defaultTheme = require('tailwindcss/defaultTheme');
const colors = require('tailwindcss/colors');

module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './vendor/filament/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/*.blade.php',
        './resources/views/**/*.blade.php',
        './app/Themes/TallForms/*.php',
    ],
    safelist: [
        {
            pattern: /col-span-(1|2|3|4|5|6|7|8|9|10|11|12)/,
            variants: ['sm', 'md', 'lg', 'xl', '2xl'],
        },
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Nunito', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                current: 'currentColor',
                gray: colors.stone,
                secondary: {
                    //lots of colors like in "primary"
                },
                primary: {
                    50: '#f5f8fb',
                    100: '#ebf2f8',
                    200: '#ccdeed',
                    300: '#adcae2',
                    400: '#70a2cd',
                    500: '#337ab7',
                    DEFAULT: '#337ab7',
                    600: '#2e6ea5',
                    700: '#265c89',
                    800: '#1f496e',
                    900: '#193c5a'
                },
                danger: {
                   // lots of #
                },
                success: {
                   // lots of #
                }
            },
        },
    },

    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('@tailwindcss/aspect-ratio')
    ],
};

```
