### DISCUSSION TITLE
Control table column width

### DISCUSSION THREAD

**Discussion by howdu** [filamentphp/filament#5429] [Ideas]
Allow for column width to be controlled easily without writing custom CSS. 

It would be useful to prevent a column from growing while also ability to set a maximum width. 

E.g icon column with action needs this custom CSS:
```css
.filament-table-header-cell-status {
    width: 1%
}
.filament-table-cell-status button {
    display: inline-block;
    width: auto;
}
```
