### DISCUSSION TITLE
How to set the width of resource table?

### DISCUSSION THREAD

**Discussion by jigujigu** [filamentphp/filament#7016] [Help]
Hi All,

Since my resource only have 1 field, how I can set the table resource become more smaller.

Thanks

**Comment by pboivin** [comment]
Hi @jigujigu, this can be done with custom CSS

**Reply by jigujigu** [reply]
Can you give me example please...

I don't know how to do it :(

thank you

**Reply by pboivin** [reply]
Use this to register a CSS file:
https://filamentphp.com/docs/2.x/admin/appearance#including-frontend-assets

The rest is basic CSS, here's a quick example for a `PostResource` :
```css
.filament-resources-posts .filament-tables-component {
  max-width: 50%;
}
```
