### DISCUSSION TITLE
I want to change background color for the Section::make()

### DISCUSSION THREAD

**Discussion by alkoumi** [filamentphp/filament#8286] [Help] [answered]
I have many sections in my form, I want to change the background color for the section
```
    public static function form(Form $form): Form
    {
        return $form
            ->schema([

                Section::make(__('Main Informations'))
                    ->schema([
                        TextInput::make('name'),
                        TextInput::make('mobile'),
                                        ]),

                   Section::make(__('General Informations'))
                    ->schema([
                           Select::make('gender_id'),
                           Select::make('preacher_id')
                                       ])
                ]);
    }
```

How can I do that PLEASE HELP!

**Comment by leandrocfe** [comment]
`->extraAttributes(['style' => 'background-color:#ccc'])`

**Reply by alkoumi** [reply]
Thank you for your good Answer, What about if I want to override the tailwind attributes like ```dark:bg-gray```

**Reply by rahat1994** [reply]
are you looking for something like this [Filament Theme](https://filamentphp.com/docs/3.x/panels/themes#creating-a-custom-theme)

**Reply by leandrocfe** [reply, marked as answer]
via classes / custom theme
`->extraAttributes(['class' => 'xx'])`
[creating-a-custom-theme](https://filamentphp.com/docs/3.x/panels/themes#creating-a-custom-theme)

via css
```css
->extraAttributes([
    'style' => '
        background-color: #ccc;
        @media (prefers-color-scheme: dark) {
            background-color: #333
        }'
])
```
