### DISCUSSION TITLE
Fileupload PDF extra height issue

### DISCUSSION THREAD

**Discussion by HeinMinThant117** [filamentphp/filament#8830] [Help]
There seems to be a big space for pdf previews on filament v3 FileUpload.

Here is my code:
```php
FileUpload::make('document_link')
                            ->label('Document')
                            ->disk('s3')
                            ->directory('user-documents')
                            ->visibility('public')
                            ->openable()
                            ->acceptedFileTypes(['application/pdf'])
 ```
 
 Here is the image of the issue:
 
![image](https://github.com/filamentphp/filament/assets/65489487/523e98dd-c110-4a2e-b4ea-99ed815f5998)

**Comment by abdullafahem** [comment]
Same issue did you solve it?

**Comment by SupianIDz** [comment]
I solved it by overriding the height of filepond.
cc : @abdullafahem @HeinMinThant117 

```css
.filepond--root {
    height: 46px !important;
}

.filepond--root .filepond--drop-label {
    height: 46px !important;
    min-height: 46px !important;
}
```
<img width="860" alt="Screenshot 2024-03-09 at 12 59 54" src="https://github.com/filamentphp/filament/assets/37969970/05fb290e-d17e-478e-b129-7651fbe447a7">
