### DISCUSSION TITLE
How to change tooltips color?

### DISCUSSION THREAD

**Discussion by devhoussam1998** [filamentphp/filament#9439] [Help]
https://filamentphp.com/docs/3.x/infolists/entries/getting-started#tooltips

**Comment by VincvanAs** [comment]
Create a custom layout https://filamentphp.com/docs/3.x/infolists/layout/custom

**Comment by cawecoy** [comment]
I style it throught this CSS code:

```CSS
.tippy-box[data-theme~=light]{
    background-color: rgb(var(--gray-700)) !important;
    color: rgb(255 255 255);
}
.tippy-box[data-theme~=light][data-placement^=top]>.tippy-arrow:before{
    border-top-color: rgb(var(--gray-700)) !important;
}
.tippy-box[data-theme~=light][data-placement^=right]>.tippy-arrow:before{
    border-right-color: rgb(var(--gray-700)) !important;
}
.tippy-box[data-theme~=light][data-placement^=bottom]>.tippy-arrow:before{
    border-bottom-color: rgb(var(--gray-700)) !important;
}
.tippy-box[data-theme~=light][data-placement^=left]>.tippy-arrow:before{
    border-left-color: rgb(var(--gray-700)) !important;
}
```

FilamentPHP uses [this package](https://github.com/ryangjchandler/alpine-tooltip?tab=readme-ov-file) which in turn uses Tippy.js. I've found that CSS on its official website: https://atomiks.github.io/tippyjs/v6/themes/
