### DISCUSSION TITLE
sticky header for table?

### DISCUSSION THREAD

**Discussion by ghost** [filamentphp/filament#9613] [Help]
Is there a way to fix the header of a table? It would be very helpful, especially for long tables.

**Comment by leandrocfe** [comment]
Maybe via css customizing a [theme](https://filamentphp.com/docs/3.x/panels/themes#creating-a-custom-theme)
But you could customize the [number of records](https://filamentphp.com/docs/3.x/tables/advanced#customizing-the-default-pagination-page-option) and use [toggleble](https://filamentphp.com/docs/3.x/tables/columns/getting-started#toggling-column-visibility) for long tables..

**Comment by ghost** [comment]
I tried it with the following custom CSS, but unfortunately it still doesn't work :-(

```
.fi-ta-table thead{
    background: green !important;
    color: white !important;
    position: sticky !important;
}
```

**Comment by ghost** [comment]
> Maybe via css customizing a [theme](https://filamentphp.com/docs/3.x/panels/themes#creating-a-custom-theme) But you could customize the [number of records](https://filamentphp.com/docs/3.x/tables/advanced#customizing-the-default-pagination-page-option) and use [toggleble](https://filamentphp.com/docs/3.x/tables/columns/getting-started#toggling-column-visibility) for long tables..

Unfortunately, the long table is required, otherwise it would indeed be possible to work with "pagination" or "toggle".

**Comment by kismonguz** [comment]
To work properly, you have to unset some overflow attributes of parent nodes.
You should double check if it mess up anything, but try this:
```css
.fi-ta-table thead {
    position: sticky !important;
    top: 4rem;
    z-index: 50;
}
/* opacity does not looks good in dark mode, so insert the corresponding bg color here */
.fi-ta-table thead:is(:where(.dark) .dark\:bg-white\/5){
    background-color: rgb(36 36 39);
}

.fi-ta-content{
    overflow: unset!important;
}

.fi-ta-ctn{
    overflow: unset!important;
}
```
